version: '3.3'
services:
  checkout-api:
    container_name: checkout-api
    restart: always
    environment:
      - BILL_SERVICE_URL=http://localhost:3000
      - LOGISTIC_SERVICE_URL=http://localhost:3001
    build:
      context: .
      dockerfile: ./apps/checkout/Dockerfile
    ports:
      - "3000:3000"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: