version: '3.3'

networks:
  app-network: {}

services:
  bill-api:
    container_name: bill-api
    restart: always
    build:
      context: .
      dockerfile: ./apps/bill/Dockerfile
    environment:
      DB_HOST: 'host.docker.internal'
      DB_PORT: '3306'
      DB_USER_NAME: 'user'
      DB_PASSWORD: 'password'
      DB_DATA_BASE: 'db'
    ports:
      - "3001:3000"
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - app-network

volumes:
  my-db: